"""add status field to projects

Revision ID: 0390ed2ce36d
Revises: 3faacbccf5bb
Create Date: 2026-06-14 11:15:16.809096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0390ed2ce36d'
down_revision: Union[str, None] = '3faacbccf5bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('status', sa.String(length=20), nullable=True, server_default='idle'))
    op.add_column('project', sa.Column('settings_json', sa.Text(), nullable=True, server_default='{}', comment='Project settings as JSON'))
    op.add_column('project', sa.Column('ignored_patterns', sa.Text(), nullable=True, server_default='tests|migrations|__pycache__|venv|node_modules'))
    op.add_column('project', sa.Column('output_format', sa.String(length=20), nullable=True, server_default='markdown'))
    op.add_column('project', sa.Column('priority_modules', sa.Text(), nullable=True, server_default='', comment='Comma-separated list of priority module paths'))
    op.add_column('projectsnapshot', sa.Column('files_analyzed', sa.Text(), nullable=True, server_default='', comment='Comma-separated list of analyzed file paths'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projectsnapshot', 'files_analyzed')
    op.drop_column('project', 'priority_modules')
    op.drop_column('project', 'output_format')
    op.drop_column('project', 'ignored_patterns')
    op.drop_column('project', 'settings_json')
    op.drop_column('project', 'status')
    # ### end Alembic commands ###
